### ISSUE TITLE
your dragging control to dynamically reassing polygon size

### ISSUE THREAD

**Issue by dscsoft** [thatjpk/leaflet.polydrag#1]
Hi, wonderfull control. I have used it to dynamically create a polygon over map. 
Find it at: www.diegosoto.com/poly_drag_resize.aspx

**Comment by thatjpk** [comment]
Nifty!  Glad you found it useful. :)
You might also find [this](https://github.com/jacobtoye/Leaflet.draw) leaflet plugin interesting.  I'm using it and my drag handler to do roughly the same thing.
