### ISSUE TITLE
leaflet 1.0.0

### ISSUE THREAD

**Issue by porjo** [thatjpk/leaflet.polydrag#5]
@snkashis could this be updated for Leaflet 1.0.0 ? (posting here as snkashis' repo doesn't have issues enabled)

**Comment by snkashis** [comment]
Here you go, take a look. https://github.com/snkashis/leaflet.polydrag/tree/1.0 
Polygons work, polylines don't. Haven't worked on this in a while.

**Comment by porjo** [comment]
Thanks, it works!
